@apiKey = 2fb6e5addcmsh1322df483636808p164ae7jsn0a8259f9946f
@apiHost = open-weather13.p.rapidapi.com

### Tester la météo pour Paris
GET https://{{apiHost}}/city/paris/FR
X-RapidAPI-Key: {{apiKey}}
X-RapidAPI-Host: {{apiHost}}

### Tester les prévisions météo pour les 5 prochains jours pour Paris (Latitude: 48.8566, Longitude: 2.3522)
GET https://open-weather13.p.rapidapi.com/city/fivedaysforcast/48.8566/2.3522
X-RapidAPI-Key: {{apiKey}}
X-RapidAPI-Host: open-weather13.p.rapidapi.com


